export const data = [
    {
      id: 1,
      title: "Blood in the Mobile",
      description:"bortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
      image: "./assets/img/blood_in_the_mobile.webp",
      genre: "Documentary",
      price: 16,
    },
    {
      id: 2,
      title: "Toe to Toe",
      description:"bortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
      image: "./assets/img/toe_to_toe-.webp",
      genre: "Drama",
      price: 56,
    },
    {
      id: 3,
      title: "Country Strong",
      description:"bortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
      image: "./assets/img/country-strong.webp",
      genre: "Drama|Musical|Romance",
      price: 22,
    },
    {
      id: 4,
      title: "Barbershop 2: Back in Business",
      description:"bortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
      image: "assets/img/barbershop_2_back_in_business.webp",
      genre: "Comedy",
      price: 19,
    },
    {
      id: 5,
      title: "Filming 'Othello'",
      description:"bortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
      image: "./assets/img/othello-2001.webp",
      genre: "Documentary",
      price: 79,
    },
    {
      id: 6,
      title: "Noise",
      description:"bortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
      image: "./assets/img/noise.webp",
      genre: "Drama|Thriller",
      price: 5,
    },
    {
      id: 7,
      title: "Parasite",
      description:"bortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
      image: "./assets/img/parasite.webp",
      genre: "Horror|Sci-Fi",
      price: 99,
    },
    {
      id: 8,
      title: "Boiling Point (3-4 x jûgatsu)",
      description:"bortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
      image: "./assets/img/Boiling_Point_(3-4xjûgatsu).webp",
      genre: "Action|Comedy|Crime",
      price: 39,
    },
    {
      id: 9,
      title: "Elegy",
      description:"bortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
      image: "./assets/img/elegy.webp",
      genre: "Drama|Romance",
      price: 54,
    },
    {
      id: 10,
      title: "Mississippi Grind",
      description:"bortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
      image: "assets/img/mississipi_grind.webp",
      genre: "Drama",
      price: 48,
    },
    {
      id: 11,
      title: "Lost in La Mancha",
      description:"bortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
      image: "./assets/img/lost_in_la_mancha.webp",
      genre: "Documentary",
      price: 39,
    },
    {
      id: 12,
      title: "Stockholm Stories",
      description:"bortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
      image: "./assets/img/stockholm_stories.webp",
      genre: "Drama",
      price: 2,
    },
  ];